# fish completion for solx
complete -c solx -f
complete -c solx -n __fish_use_subcommand -s h -l help -d 'Show this help message and exit.'
complete -c solx -n __fish_use_subcommand -l version -d 'Show version and exit.'
complete -c solx -n __fish_use_subcommand -l json -d 'Force JSON output (machine-readable).'
complete -c solx -n __fish_use_subcommand -a init -d 'Write a starter config.toml.'
complete -c solx -n '__fish_seen_subcommand_from init' -s f -l force -s y -l yes -d 'Overwrite without prompting.'
complete -c solx -n '__fish_seen_subcommand_from init' -l json -d 'Force JSON output (machine-readable).'
complete -c solx -n '__fish_seen_subcommand_from init' -s h -l help -d 'Show this help message and exit.'
complete -c solx -n __fish_use_subcommand -a keep -d 'Renew CSV-flagged scratch files filtered by the keep block in config.'
complete -c solx -n '__fish_seen_subcommand_from keep' -l stage -x -a 'all pending over90 inactive' -d 'Which warning CSVs to read.'
complete -c solx -n '__fish_seen_subcommand_from keep' -l csv-dir -r -F -d 'Directory holding Sol\'s warning CSVs.'
complete -c solx -n '__fish_seen_subcommand_from keep' -l solkeep -r -F -d 'Path to a gitignore-style keep-list.'
complete -c solx -n '__fish_seen_subcommand_from keep' -s j -l jobs -x -d 'Parallel touch workers.'
complete -c solx -n '__fish_seen_subcommand_from keep' -s y -l yes -s f -l force -d 'Skip confirmation prompt.'
complete -c solx -n '__fish_seen_subcommand_from keep' -s n -l dry-run -d 'Print plan without executing.'
complete -c solx -n '__fish_seen_subcommand_from keep' -s v -l verbose -d 'Verbose plan + progress.'
complete -c solx -n '__fish_seen_subcommand_from keep' -l json -d 'Force JSON output (machine-readable).'
complete -c solx -n '__fish_seen_subcommand_from keep' -s h -l help -d 'Show this help message and exit.'
complete -c solx -n __fish_use_subcommand -a jump -d 'Drop into a shell on the job\'s compute node (= solx job jump).'
complete -c solx -n '__fish_seen_subcommand_from jump' -s q -l quiet -d 'Suppress the nesting / most-recent heads-up.'
complete -c solx -n '__fish_seen_subcommand_from jump' -l json -d 'Force JSON output (machine-readable).'
complete -c solx -n '__fish_seen_subcommand_from jump' -s h -l help -d 'Show this help message and exit.'
complete -c solx -n __fish_use_subcommand -a job -d 'Manage interactive Slurm jobs on Sol (alias: jobs).'
complete -c solx -n '__fish_seen_subcommand_from job jobs; and not __fish_seen_subcommand_from list start stop jump time' -s h -l help -d 'Show this help message and exit.'
complete -c solx -n '__fish_seen_subcommand_from job jobs; and not __fish_seen_subcommand_from list start stop jump time' -a list -d 'Print my Sol jobs.'
complete -c solx -n '__fish_seen_subcommand_from job jobs; and __fish_seen_subcommand_from list' -l json -d 'Force JSON output (machine-readable).'
complete -c solx -n '__fish_seen_subcommand_from job jobs; and __fish_seen_subcommand_from list' -s h -l help -d 'Show this help message and exit.'
complete -c solx -n '__fish_seen_subcommand_from job jobs; and not __fish_seen_subcommand_from list start stop jump time' -a start -d 'Start an interactive allocation from a config template.'
complete -c solx -n '__fish_seen_subcommand_from job jobs; and __fish_seen_subcommand_from start' -s n -l dry-run -d 'Print salloc argv without submitting.'
complete -c solx -n '__fish_seen_subcommand_from job jobs; and __fish_seen_subcommand_from start' -l timeout -x -d 'Override start_timeout (e.g. "5m", "1h").'
complete -c solx -n '__fish_seen_subcommand_from job jobs; and __fish_seen_subcommand_from start' -s h -l help -d 'Show this help message and exit.'
complete -c solx -n '__fish_seen_subcommand_from job jobs; and not __fish_seen_subcommand_from list start stop jump time' -a stop -d 'Cancel a job (prompts unless -y).'
complete -c solx -n '__fish_seen_subcommand_from job jobs; and __fish_seen_subcommand_from stop' -s y -l yes -s f -l force -d 'Skip confirmation prompt.'
complete -c solx -n '__fish_seen_subcommand_from job jobs; and __fish_seen_subcommand_from stop' -s n -l dry-run -d 'Print scancel argv without executing.'
complete -c solx -n '__fish_seen_subcommand_from job jobs; and __fish_seen_subcommand_from stop' -l json -d 'Force JSON output (machine-readable).'
complete -c solx -n '__fish_seen_subcommand_from job jobs; and __fish_seen_subcommand_from stop' -s h -l help -d 'Show this help message and exit.'
complete -c solx -n '__fish_seen_subcommand_from job jobs; and not __fish_seen_subcommand_from list start stop jump time' -a jump -d 'Drop into a shell on the job\'s compute node.'
complete -c solx -n '__fish_seen_subcommand_from job jobs; and __fish_seen_subcommand_from jump' -s q -l quiet -d 'Suppress the nesting / most-recent heads-up.'
complete -c solx -n '__fish_seen_subcommand_from job jobs; and __fish_seen_subcommand_from jump' -l json -d 'Force JSON output (machine-readable).'
complete -c solx -n '__fish_seen_subcommand_from job jobs; and __fish_seen_subcommand_from jump' -s h -l help -d 'Show this help message and exit.'
complete -c solx -n '__fish_seen_subcommand_from job jobs; and not __fish_seen_subcommand_from list start stop jump time' -a time -d 'Print remaining time (D-HH:MM:SS).'
complete -c solx -n '__fish_seen_subcommand_from job jobs; and __fish_seen_subcommand_from time' -l json -d 'Force JSON output (machine-readable).'
complete -c solx -n '__fish_seen_subcommand_from job jobs; and __fish_seen_subcommand_from time' -s h -l help -d 'Show this help message and exit.'
complete -c solx -n __fish_use_subcommand -a config -d 'Inspect and edit the solx config.'
complete -c solx -n '__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from show edit import-solkeep' -s h -l help -d 'Show this help message and exit.'
complete -c solx -n '__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from show edit import-solkeep' -a show -d 'Print the resolved config.'
complete -c solx -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from show' -l json -d 'Emit JSON.'
complete -c solx -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from show' -s h -l help -d 'Show this help message and exit.'
complete -c solx -n '__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from show edit import-solkeep' -a edit -d 'Open the config in $EDITOR.'
complete -c solx -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from edit' -s h -l help -d 'Show this help message and exit.'
complete -c solx -n '__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from show edit import-solkeep' -a import-solkeep -d 'Migrate a legacy ~/.solkeep keep-list into the config\'s keep block.'
complete -c solx -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from import-solkeep' -l solkeep -r -F -d 'Keep-list to import (default: ~/.solkeep).'
complete -c solx -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from import-solkeep' -s f -l force -d 'Accept a lossy import.'
complete -c solx -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from import-solkeep' -l json -d 'Force JSON output (machine-readable).'
complete -c solx -n '__fish_seen_subcommand_from config; and __fish_seen_subcommand_from import-solkeep' -s h -l help -d 'Show this help message and exit.'
complete -c solx -n __fish_use_subcommand -a completions -d 'Emit a shell completion script (bash, zsh, or fish).'
complete -c solx -n '__fish_seen_subcommand_from completions' -s h -l help -d 'Show this help message and exit.'
complete -c solx -n '__fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from bash zsh fish' -a 'bash zsh fish'
complete -c solx -n __fish_use_subcommand -a version -d 'Show version and exit (alias of --version).'
complete -c solx -n '__fish_seen_subcommand_from version' -s h -l help -d 'Show this help message and exit.'
complete -c solx -n __fish_use_subcommand -a help -d 'Show help and exit (alias of --help).'
complete -c solx -n '__fish_seen_subcommand_from help' -s h -l help -d 'Show this help message and exit.'
